# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Test
    ports:
    - "15432:80"